<?php

namespace AppBundle\Repository;

/**
 * JuridicFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuridicFormRepository extends \Doctrine\ORM\EntityRepository
{
}
